Airflow Dockerfile
att-comdev/dockerfiles pull request #96
Opened 2017-05-19 00:47 UTC by eanylin

Dockerfiles for Airflow

2017-05-19 16:56 UTC, alanmeadows requested changes

2017-05-19 16:56 UTC, alanmeadows commented on airflow/config/airflow.cfg
> +[core]
This is a fine default, obviously we will want to override this in the chart.  Will comment there on how.

2017-05-19 16:56 UTC, alanmeadows commented on airflow/script/entrypoint.sh
> +CMD="airflow"
Ideally, we simply extract these from airflow.cfg, rather then needing to define them both in the config and as environment variables to the container. Requires a little chopping voodoo on the strings in the cfg as they are not in this format. Also, it looks like these are hard coded, and that if given over the environment (via k8s pod) they would be ignored.

2017-05-19 17:46 UTC, larryrensing commented on airflow/script/entrypoint.sh
> +if [ "$1" = "webserver" ] || [ "$1" = "worker" ] || [ "$1" = "scheduler" ] || [ "$1" = "flower" ] ; then
unless i'm mistaken -- you should be able to remove these lines and instead leverage a kubernetes entrypoint to wait until postgres and rabbit have endpoints within kubernetes

2017-05-24 23:27 UTC, alanmeadows commented on airflow/script/entrypoint.sh
> +if [ "$1" = "webserver" ] || [ "$1" = "worker" ] || [ "$1" = "scheduler" ] || [ "$1" = "flower" ] ; then
agreed

2017-05-26 17:49 UTC, eanylin commented on airflow/script/entrypoint.sh
> +if [ "$1" = "webserver" ] || [ "$1" = "worker" ] || [ "$1" = "scheduler" ] || [ "$1" = "flower" ] ; then
Agree.  Will leverage on kubernetes entrypoint.

2017-06-12 22:32 UTC, merged